name: are_you_elf
description: A new Flutter project.
version: 1.0.1+2

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+7
  path: ^1.8.3
  permission_handler: ^11.1.0
  google_mlkit_commons: ^0.6.1
  google_mlkit_face_detection: ^0.9.0
  tflite_flutter: ^0.10.4
  image: ^4.1.3
  path_provider: ^2.1.1
  image_picker: ^1.0.5
  exif: ^3.3.0
  google_fonts: ^6.1.0
  pytorch_lite: ^4.2.4
  flutter_native_splash: ^2.3.9
  app_tracking_transparency: ^2.0.4
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true